from enum import Enum

class ConversationState(str, Enum):
    IDLE = "IDLE"
    MAIN_MENU = "MAIN_MENU"
    MENU_HEALTH = "MENU_HEALTH"
    MENU_MARKET = "MENU_MARKET"
    AWAITING_DOUBT_INPUT = "AWAITING_DOUBT_INPUT"

    # Diagnostics
    DIAGNOSTICS_SELECT = "DIAGNOSTICS_SELECT"
    DIAGNOSTICS_AWAITING_IMAGE = "DIAGNOSTICS_AWAITING_IMAGE"
    DIAGNOSTICS_AWAITING_AUDIO = "DIAGNOSTICS_AWAITING_AUDIO"
    DIAGNOSTICS_PROCESSING = "DIAGNOSTICS_PROCESSING"

    # Registration
    REGISTRATION_NAME = "REGISTRATION_NAME"
    REGISTRATION_PHONE = "REGISTRATION_PHONE"
    REGISTRATION_REGION = "REGISTRATION_REGION"
    REGISTRATION_CAPACITY = "REGISTRATION_CAPACITY"
    REGISTRATION_PRACTICES = "REGISTRATION_PRACTICES"
    REGISTRATION_CONFIRM = "REGISTRATION_CONFIRM"

    # Harvest
    HARVEST_YARD_ID = "HARVEST_YARD_ID"
    HARVEST_HIVES = "HARVEST_HIVES"
    HARVEST_VOLUME = "HARVEST_VOLUME"
    HARVEST_VARIETAL = "HARVEST_VARIETAL"
    HARVEST_IMAGE = "HARVEST_IMAGE"

    # Transfer Custody Flow
    TRANSFER_BATCH_ID = "TRANSFER_BATCH_ID"
    TRANSFER_BUYER_ID = "TRANSFER_BUYER_ID"

    # Settings Flow
    SETTINGS_CHOOSE_LANGUAGE = "SETTINGS_CHOOSE_LANGUAGE"
    TRANSFER_CONFIRM = "TRANSFER_CONFIRM"

    # Verify
    BATCH_STATUS_AWAITING_ID = "BATCH_STATUS_AWAITING_ID"
