export enum ConversationState {
  IDLE = 'IDLE',
  MAIN_MENU = 'MAIN_MENU',

  // Registration flow
  REGISTRATION_NAME = 'REGISTRATION_NAME',
  REGISTRATION_PHONE = 'REGISTRATION_PHONE',
  REGISTRATION_EMAIL = 'REGISTRATION_EMAIL',
  REGISTRATION_REGION = 'REGISTRATION_REGION',
  REGISTRATION_KVIC = 'REGISTRATION_KVIC',
  REGISTRATION_CAPACITY = 'REGISTRATION_CAPACITY',
  REGISTRATION_PRACTICES = 'REGISTRATION_PRACTICES',
  REGISTRATION_CONFIRM = 'REGISTRATION_CONFIRM',

  // AI Diagnostics Flow (Image / Audio)
  DIAGNOSTICS_SELECT = 'DIAGNOSTICS_SELECT',
  DIAGNOSTICS_AWAITING_IMAGE = 'DIAGNOSTICS_AWAITING_IMAGE',
  DIAGNOSTICS_AWAITING_AUDIO = 'DIAGNOSTICS_AWAITING_AUDIO',
  DIAGNOSTICS_PROCESSING = 'DIAGNOSTICS_PROCESSING',

  // Hive Status
  HIVE_STATUS = 'HIVE_STATUS',
  HIVE_SELECT = 'HIVE_SELECT',

  // Batch Status
  BATCH_STATUS_AWAITING_ID = 'BATCH_STATUS_AWAITING_ID',

  // Health Report
  HEALTH_REPORT = 'HEALTH_REPORT',

  // Language
  LANGUAGE_SELECT = 'LANGUAGE_SELECT',
}
